#!/usr/bin/env python

import sys

from rqt_duckpit.my_module import RQTDuckpit
from rqt_gui.main import Main

plugin = 'rqt_duckpit'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))